# Generated by Django 2.2.16 on 2022-09-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220904_2158'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='self_assignment',
        ),
    ]
